# Generated by Django 6.0.2 on 2026-02-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_last_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_seen',
            new_name='lastSeen',
        ),
    ]
